name: Unit Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install the library
      run: |
        uv sync --frozen
    - name: Run the unit tests
      run: |
        uv run python tests/test_methods.py
